
package cl.movistar.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HistoricoRequerimientosImpl", targetNamespace = "http://services.movistar.cl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HistoricoRequerimientosImpl {


    /**
     * 
     * @param criterio
     * @return
     *     returns cl.movistar.services.HistoricoResponse
     */
    @WebMethod
    @WebResult(name = "consultaHistoricoCriterioReturn", targetNamespace = "http://services.movistar.cl")
    @RequestWrapper(localName = "consultaHistoricoCriterio", targetNamespace = "http://services.movistar.cl", className = "cl.movistar.services.ConsultaHistoricoCriterio")
    @ResponseWrapper(localName = "consultaHistoricoCriterioResponse", targetNamespace = "http://services.movistar.cl", className = "cl.movistar.services.ConsultaHistoricoCriterioResponse")
    public HistoricoResponse consultaHistoricoCriterio(
        @WebParam(name = "criterio", targetNamespace = "http://services.movistar.cl")
        CriterioRequest criterio);

    /**
     * 
     * @param cliente
     * @return
     *     returns cl.movistar.services.HistoricoResponse
     */
    @WebMethod
    @WebResult(name = "consultaHistoricoClienteReturn", targetNamespace = "http://services.movistar.cl")
    @RequestWrapper(localName = "consultaHistoricoCliente", targetNamespace = "http://services.movistar.cl", className = "cl.movistar.services.ConsultaHistoricoCliente")
    @ResponseWrapper(localName = "consultaHistoricoClienteResponse", targetNamespace = "http://services.movistar.cl", className = "cl.movistar.services.ConsultaHistoricoClienteResponse")
    public HistoricoResponse consultaHistoricoCliente(
        @WebParam(name = "cliente", targetNamespace = "http://services.movistar.cl")
        ClienteRequest cliente);

}
