
package cl.movistar.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HistoricoRequerimientosImplService", targetNamespace = "http://services.movistar.cl", wsdlLocation = "file:/C:/Desarrollo/HistoricoRequerimientoWebservice/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/HistoricoRequerimientosImpl.wsdl")
public class HistoricoRequerimientosImplService
    extends Service
{

    private final static URL HISTORICOREQUERIMIENTOSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTORICOREQUERIMIENTOSIMPLSERVICE_EXCEPTION;
    private final static QName HISTORICOREQUERIMIENTOSIMPLSERVICE_QNAME = new QName("http://services.movistar.cl", "HistoricoRequerimientosImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Desarrollo/HistoricoRequerimientoWebservice/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/HistoricoRequerimientosImpl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTORICOREQUERIMIENTOSIMPLSERVICE_WSDL_LOCATION = url;
        HISTORICOREQUERIMIENTOSIMPLSERVICE_EXCEPTION = e;
    }

    public HistoricoRequerimientosImplService() {
        super(__getWsdlLocation(), HISTORICOREQUERIMIENTOSIMPLSERVICE_QNAME);
    }

    public HistoricoRequerimientosImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTORICOREQUERIMIENTOSIMPLSERVICE_QNAME, features);
    }

    public HistoricoRequerimientosImplService(URL wsdlLocation) {
        super(wsdlLocation, HISTORICOREQUERIMIENTOSIMPLSERVICE_QNAME);
    }

    public HistoricoRequerimientosImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTORICOREQUERIMIENTOSIMPLSERVICE_QNAME, features);
    }

    public HistoricoRequerimientosImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoricoRequerimientosImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistoricoRequerimientosImpl
     */
    @WebEndpoint(name = "HistoricoRequerimientosImpl")
    public HistoricoRequerimientosImpl getHistoricoRequerimientosImpl() {
        return super.getPort(new QName("http://services.movistar.cl", "HistoricoRequerimientosImpl"), HistoricoRequerimientosImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistoricoRequerimientosImpl
     */
    @WebEndpoint(name = "HistoricoRequerimientosImpl")
    public HistoricoRequerimientosImpl getHistoricoRequerimientosImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.movistar.cl", "HistoricoRequerimientosImpl"), HistoricoRequerimientosImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTORICOREQUERIMIENTOSIMPLSERVICE_EXCEPTION!= null) {
            throw HISTORICOREQUERIMIENTOSIMPLSERVICE_EXCEPTION;
        }
        return HISTORICOREQUERIMIENTOSIMPLSERVICE_WSDL_LOCATION;
    }

}
